@id = 67204f448b1a960a6e699437
@collection = myCollection

###

POST http://localhost:3000/insert
Content-Type: application/json

{
  "collection": "{{collection}}",
  "document": {
    "name": "John",
    "age": 30
  }
}

###

GET http://localhost:3000/find/{{collection}}
Content-Type: application/json

###

DELETE http://localhost:3000/delete/{{collection}}/{{id}}
Content-Type: application/json
